/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Radiant Software (64-bit)
    2023.1.1.200.1
    Soft IP Version: 2.0.0
    2025 01 20 09:42:39
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module add_48 (clk_i, rst_i, add_sub_i, data_a_re_i, data_b_re_i, result_re_o)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  clk_i;
    input  rst_i;
    input  add_sub_i;
    input  [47:0]  data_a_re_i;
    input  [47:0]  data_b_re_i;
    output  [47:0]  result_re_o;
endmodule