/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Radiant Software (64-bit)
    2023.1.1.200.1
    Soft IP Version: 1.8.0
    2023 12 29 14:15:49
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module pll_2xq_5x (clki_i, rstn_i, phasedir_i, phasestep_i, phaseloadreg_i,
    phasesel_i, clkop_o, clkos_o, clkos2_o, clkos3_o, clkos4_o, clkos5_o,
    lock_o)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  clki_i;
    input  rstn_i;
    input  phasedir_i;
    input  phasestep_i;
    input  phaseloadreg_i;
    input  [2:0]  phasesel_i;
    output  clkop_o;
    output  clkos_o;
    output  clkos2_o;
    output  clkos3_o;
    output  clkos4_o;
    output  clkos5_o;
    output  lock_o;
endmodule