/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Radiant Software (64-bit)
    2023.1.1.200.1
    Soft IP Version: 2.0.0
    2024 01 04 11:47:34
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module addct (data_a_re_i, data_b_re_i, result_re_o)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  [47:0]  data_a_re_i;
    input  [47:0]  data_b_re_i;
    output  [47:0]  result_re_o;
endmodule