/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Radiant Software (64-bit)
    2023.1.0.43.3
    Soft IP Version: 1.4.0
    2023 11 29 11:02:13
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module WEIGHT_FIFO_24x96 (wr_clk_i, rd_clk_i, rst_i, rp_rst_i, wr_en_i,
    rd_en_i, wr_data_i, full_o, empty_o, almost_full_o, rd_data_o)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  wr_clk_i;
    input  rd_clk_i;
    input  rst_i;
    input  rp_rst_i;
    input  wr_en_i;
    input  rd_en_i;
    input  [23:0]  wr_data_i;
    output  full_o;
    output  empty_o;
    output  almost_full_o;
    output  [23:0]  rd_data_o;
endmodule